services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kaplay-colyseus-server
    environment:
      - NODE_ENV=production
      - PORT=2567
      - CORS_ORIGIN=*
      - MONITOR_PASSWORD=secure_monitor_password
    ports:
      - "2567:2567"
    networks:
      - kaplay-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2567/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_SERVER_URL=http://localhost:2567
        - VITE_SERVER_WS_URL=ws://localhost:2567
    container_name: kaplay-colyseus-client
    environment:
      - SERVER_URL=http://kaplay-colyseus-server:2567
    ports:
      - "80:80"
    networks:
      - kaplay-network
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

networks:
  kaplay-network:
    driver: bridge
    name: kaplay-colyseus-network